import { Inter } from "next/font/google";
import "../globals.css";
import { Poppins } from "next/font/google";
import Image from 'next/image'

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  style: ["normal", "italic"]
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
        <Image
          src={"VR Logo Small.svg"}
          className="absolute top-10 -left-20 h-5 phone:h-5 phone:top-5 phone:left-0"
          alt="VR Logo"
          width={500}
          height={500}
          /> 
          
          {children}
    </div>
    
  );
}
