import { Inter } from "next/font/google";
import "../globals.css";
import { Poppins } from "next/font/google";
import Image from 'next/image'

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  style: ["normal", "italic"]
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({ children }) {
  return (
    <div className="w-[100%] min-w-[320px]]">
        <Image
          src={"VR Logo Small.svg"}
          className="mt-10 h-5"
          alt="VR Logo"
          width={500}
          height={500}
          /> 
          
        {children}
    </div>
    
  );
}
